stages:
  - build
  - publish

build:
  stage: build
  image: python:3.4-alpine
  before_script:
    - apk update
    - apk add make
    - apk add inkscape
    - apk add imagemagick
    - pip install sphinx==1.3

  script:
    - ./build.sh
    - mv ./rst/build public
    - ./build_en_US.sh
    - mv ./rst/build public/en
  artifacts:
    paths:
      - public
    expire_in: 10 minutes
  only:
    - master

pages:
  stage: publish
  script:
    - ls public
  artifacts:
    paths:
      - public
  only:
    - master

mirror:
  stage: publish
  image: liaohuqiu/rsync
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - >-
      [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >
      ~/.ssh/config
  script:
    - rsync -az -e ssh ./public/ gammanu@1000i100.fr:~/geconomicus
  only:
    - master
